codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "10...100"

  status:
    default:
      enabled: yes
      target: "85%"
      threshold: "3%"
    patch: no
    changes: no

comment: off
